// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.u64().name("room_id"),
  trackId: __t.u64().name("track_id"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  qx: __t.f64(),
  qy: __t.f64(),
  qz: __t.f64(),
  qw: __t.f64(),
  speed: __t.f64(),
  checkpointIndex: __t.u32().name("checkpoint_index"),
  runStartedAtMs: __t.u64().name("run_started_at_ms"),
  updatedAt: __t.timestamp().name("updated_at"),
  carId: __t.string().name("car_id"),
  liveryId: __t.string().name("livery_id"),
});
