// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  identity: __t.identity(),
  roomId: __t.u64().name("room_id"),
  trackId: __t.u64().name("track_id"),
  checkpointIndex: __t.u32().name("checkpoint_index"),
  elapsedMs: __t.u64().name("elapsed_ms"),
  createdAt: __t.timestamp().name("created_at"),
});
