// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  frameId: __t.u64().primaryKey().name("frame_id"),
  lapId: __t.u64().name("lap_id"),
  elapsedMs: __t.u64().name("elapsed_ms"),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  qx: __t.f64(),
  qy: __t.f64(),
  qz: __t.f64(),
  qw: __t.f64(),
  speed: __t.f64(),
});
