// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  trackId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  qx: __t.f64(),
  qy: __t.f64(),
  qz: __t.f64(),
  qw: __t.f64(),
  speed: __t.f64(),
  checkpointIndex: __t.u32(),
  runStartedAtMs: __t.u64(),
  carId: __t.string(),
  liveryId: __t.string(),
};
