// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CarState = __t.object("CarState", {
  identity: __t.identity(),
  roomId: __t.u64(),
  trackId: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  qx: __t.f64(),
  qy: __t.f64(),
  qz: __t.f64(),
  qw: __t.f64(),
  speed: __t.f64(),
  checkpointIndex: __t.u32(),
  runStartedAtMs: __t.u64(),
  updatedAt: __t.timestamp(),
  carId: __t.string(),
  liveryId: __t.string(),
});
export type CarState = __Infer<typeof CarState>;

export const CheckpointEvent = __t.object("CheckpointEvent", {
  eventId: __t.u64(),
  identity: __t.identity(),
  roomId: __t.u64(),
  trackId: __t.u64(),
  checkpointIndex: __t.u32(),
  elapsedMs: __t.u64(),
  createdAt: __t.timestamp(),
});
export type CheckpointEvent = __Infer<typeof CheckpointEvent>;

export const GhostFrame = __t.object("GhostFrame", {
  frameId: __t.u64(),
  lapId: __t.u64(),
  elapsedMs: __t.u64(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  qx: __t.f64(),
  qy: __t.f64(),
  qz: __t.f64(),
  qw: __t.f64(),
  speed: __t.f64(),
});
export type GhostFrame = __Infer<typeof GhostFrame>;

export const LapResult = __t.object("LapResult", {
  lapId: __t.u64(),
  identity: __t.identity(),
  roomId: __t.u64(),
  trackId: __t.u64(),
  elapsedMs: __t.u64(),
  checkpointCount: __t.u32(),
  createdAt: __t.timestamp(),
});
export type LapResult = __Infer<typeof LapResult>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  slug: __t.string(),
  trackId: __t.u64(),
  lapCount: __t.u32(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomCountdown = __t.object("RoomCountdown", {
  roomId: __t.u64(),
  startedAtMs: __t.u64(),
  startsAtMs: __t.u64(),
});
export type RoomCountdown = __Infer<typeof RoomCountdown>;

export const RoomMember = __t.object("RoomMember", {
  memberId: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
  ready: __t.bool(),
});
export type RoomMember = __Infer<typeof RoomMember>;

export const RoomRaceStart = __t.object("RoomRaceStart", {
  roomId: __t.u64(),
  startedBy: __t.identity(),
  startedAtMs: __t.u64(),
});
export type RoomRaceStart = __Infer<typeof RoomRaceStart>;

export const Track = __t.object("Track", {
  trackId: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  layoutJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type Track = __Infer<typeof Track>;
