// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import FinishLapReducer from "../finish_lap_reducer";
import JoinOrCreateRoomReducer from "../join_or_create_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PublishCarStateReducer from "../publish_car_state_reducer";
import RecordCheckpointReducer from "../record_checkpoint_reducer";
import RecordGhostFrameReducer from "../record_ghost_frame_reducer";
import SetPlayerNameReducer from "../set_player_name_reducer";

export type FinishLapParams = __Infer<typeof FinishLapReducer>;
export type JoinOrCreateRoomParams = __Infer<typeof JoinOrCreateRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PublishCarStateParams = __Infer<typeof PublishCarStateReducer>;
export type RecordCheckpointParams = __Infer<typeof RecordCheckpointReducer>;
export type RecordGhostFrameParams = __Infer<typeof RecordGhostFrameReducer>;
export type SetPlayerNameParams = __Infer<typeof SetPlayerNameReducer>;
